# Generated by Django 3.0.5 on 2020-05-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200428_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='product',
        ),
    ]
